[package]
name = "gossip-p2p"
authors = ["RAprogramm <andrey.rozanov.vl@gmail.com"]
version = "0.1.0"
edition = "2021"

[[bin]]
name = "peer"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
