[package]
name = "gossip-p2p"
authors = ["RAprogramm <andrey.rozanov.vl@gmail.com"]
version = "0.1.0"
edition = "2021"

[[bin]]
name = "peer"
path = "src/main.rs"

[dependencies]
bincode = "1.3.3"
message-io = "0.18.1"
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
